# Generated by Django 3.2.6 on 2021-08-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
