# Generated by Django 3.2.6 on 2021-08-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_delete_twitchviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=25)),
                ('chat_count', models.IntegerField()),
            ],
        ),
    ]
