# Generated by Django 3.2.6 on 2021-08-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.TextField(),
        ),
    ]
