# Generated by Django 3.2.6 on 2021-08-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AlterField(
            model_name='project',
            name='name_text',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
