# Generated by Django 3.2.6 on 2021-08-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20210824_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_id',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitchuser',
            name='user_id',
            field=models.CharField(default=0, max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='twitchuser',
            name='name_text',
            field=models.CharField(max_length=25),
        ),
    ]
