# Generated by Django 3.2.6 on 2021-08-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20210825_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
